name: Build Pages

on:
  push:
    branches:
      - master
    paths:
      - '**.ts'
      - '.github/CNAME'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-l10n-tools gettext

      - name: Build translations
        run: |
          export LCONVERT_BIN="/usr/lib/qt6/bin/lconvert"
          export LRELEASE_BIN="/usr/lib/qt6/bin/lrelease"
          export LUPDATE_BIN="/usr/lib/qt6/bin/lupdate"
          ./release.sh

      - name: Move directory
        run: |
          mv build _site
          cp .github/CNAME _site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
